### ISSUE TITLE
Bug in EncoderLightManual

### ISSUE THREAD

**Issue by iosonopersia** [vaimee/desmo-dapp#14] opened 2022-09-06 10:31 UTC
I found a bug while writing tests for the decoding happening inside the SDK.

In the `main` branch (I don't know if you already fixed this in one of the open PRs), you forgot to multiply float values by `10**precision`.
I would do it before this line: https://github.com/vaimee/desmo-dapp/blob/f04124e3970d2a2f6ba74ebfd3aaced507c4a7fa/DApp/src/component/encoder/EncoderLightManual.ts#L101

Example:
```typescript
sanitizzeNumberValue *= 10**precision;
```

**Comment by relu91** [comment] 2022-09-06 12:20
To solve this issue, can we use the code implemented in the SDK? We already have the dependency.

**Comment by iosonopersia** [comment] 2022-09-06 12:26
As a matter of fact, I don't really think the DApp should contain code to _decode_ query results, as its job is to _encode_ them only.

But I don't know anything about this codebase, so it's up to you. At the moment, decoder functions are not exported by the SDK library, as they are used only internally.

**Comment by FerrariAndrea** [comment] 2022-09-10 08:15
@iosonopersia sorry, this is not a bug, the encoder function requires the number already multiplied for it precision, that because in the past this was needed. I need to understand how I can rework it, it would be better if we pass the real number instead an already edited one.

You can see that operation here:
https://github.com/vaimee/desmo-dapp/blob/010e8c5f862cb2ed277d7a2785d0299019222fd4/DApp/src/model/Result.ts#L53-L60

I will change it following your tip. The function will be: `encodeNumber(realValue)` instead of `encodeNumber(integerNumber,numberPrecision)`

**Comment by iosonopersia** [comment] 2022-09-10 08:25
Don't worry, I was just a bit confused while trying to understand how the result value was encoded. It's not a high priority change, it's just that having all the encoding logic inside the encoder module would be easier to read and understand 👍

**Comment by FerrariAndrea** [comment] 2022-09-12 12:06
Improved in PR #13 I will close that issue when the PR will be merged on the main branch

**Comment by FerrariAndrea** [comment] 2022-09-12 17:49
Closed by PR #13

**Closed as completed by FerrariAndrea** 2022-09-12 17:49 UTC
Labels: type: code style
